// Generated by AUJava Transpiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// Forward Struct Declarations
struct Vehicle;
struct Car;
struct Main;
struct Engine;

// Struct Definitions
struct Vehicle {
    int weight;
    void (*function_setWeight)(void *caller, int);
    int (*function_calculateTax)(void *caller, int);
};

struct Car {
    struct Vehicle super;
    bool isElectric;
    struct Engine* engine;
    void (*function_setWeight)(void *caller, int);
    int (*function_calculateTax)(void *caller, int);
    void (*function_setEngine)(void *caller, struct Engine*);
};

struct Main {
};

struct Engine {
    int horsepower;
    int (*function_getHorsepower)(void *caller);
    void (*function_setHorsepower)(void *caller, int);
};


// Global Static Fields
int Vehicle_vehicleCount = 0;

// Function Forward Declarations
struct Vehicle* new_Vehicle();
struct Car* new_Car();
struct Main* new_Main();
struct Engine* new_Engine();
void Vehicle_incrementCount(void);
void Vehicle_function_setWeight(void *caller, int w);
int Vehicle_function_calculateTax(void *caller, int baseTax);
void Car_function_setEngine(void *caller, struct Engine* e);
int Car_function_calculateTax(void *caller, int baseTax);
void Engine_function_setHorsepower(void *caller, int hp);
int Engine_function_getHorsepower(void *caller);

// Constructors
struct Vehicle* new_Vehicle() {
    struct Vehicle *instance = (struct Vehicle *) malloc(sizeof(struct Vehicle));
    instance->function_setWeight = (void *) Vehicle_function_setWeight;
    instance->function_calculateTax = (void *) Vehicle_function_calculateTax;
    return instance;
}

struct Car* new_Car() {
    struct Car *instance = (struct Car *) malloc(sizeof(struct Car));
    struct Vehicle *parent_inst = new_Vehicle();
    instance->super = *parent_inst;
    free(parent_inst);
    instance->function_setWeight = (void *) Vehicle_function_setWeight;
    instance->super.function_setWeight = (void *) Vehicle_function_setWeight;
    instance->function_calculateTax = (void *) Car_function_calculateTax;
    instance->super.function_calculateTax = (void *) Car_function_calculateTax;
    instance->function_setEngine = (void *) Car_function_setEngine;
    return instance;
}

struct Main* new_Main() {
    struct Main *instance = (struct Main *) malloc(sizeof(struct Main));
    return instance;
}

struct Engine* new_Engine() {
    struct Engine *instance = (struct Engine *) malloc(sizeof(struct Engine));
    instance->function_getHorsepower = (void *) Engine_function_getHorsepower;
    instance->function_setHorsepower = (void *) Engine_function_setHorsepower;
    return instance;
}


// Method Implementations
void Vehicle_incrementCount(void) {
    int _t_2 = 1;
    int _t_3 = Vehicle_vehicleCount + _t_2;
    Vehicle_vehicleCount = _t_3;
}

void Vehicle_function_setWeight(void *caller, int w) {
    ((struct Vehicle*) caller)->weight = w;
}

int Vehicle_function_calculateTax(void *caller, int baseTax) {
    int _t_4 = 2;
    int _t_5 = ((struct Vehicle*) caller)->weight * _t_4;
    int _t_6 = baseTax + _t_5;
    return _t_6;
}

void Car_function_setEngine(void *caller, struct Engine* e) {
    ((struct Car*) caller)->engine = e;
}

int Car_function_calculateTax(void *caller, int baseTax) {
    if (!(((struct Car*) caller)->isElectric)) goto if_else_1;
    {
    int _t_7 = 2;
    int _t_8 = baseTax / _t_7;
    return _t_8;
    }
    goto if_end_2;
    if_else_1:
    {
    int _t_9 = 3;
    int _t_10 = ((struct Car*) caller)->super.weight * _t_9;
    int _t_11 = baseTax + _t_10;
    return _t_11;
    }
    if_end_2:
}

void Engine_function_setHorsepower(void *caller, int hp) {
    ((struct Engine*) caller)->horsepower = hp;
}

int Engine_function_getHorsepower(void *caller) {
    return ((struct Engine*) caller)->horsepower;
}


// Program Main Entry Point
int main() {
    int _t_1 = 0;
    Vehicle_vehicleCount = _t_1;
    Vehicle_incrementCount();
    Vehicle_incrementCount();
    printf("%d\n", Vehicle_vehicleCount);
    struct Engine *_t_14 = new_Engine();
    struct Engine* eng = (struct Engine*) _t_14;
    int _t_15 = 300;
    eng->function_setHorsepower(eng, _t_15);
    int _t_17 = eng->function_getHorsepower(eng);
    printf("%d\n", _t_17);
    struct Car *_t_18 = new_Car();
    struct Car* myCar = (struct Car*) _t_18;
    int _t_19 = 1000;
    myCar->function_setWeight(myCar, _t_19);
    bool _t_21 = false;
    myCar->isElectric = _t_21;
    myCar->function_setEngine(myCar, eng);
    printf("%d\n", myCar->super.weight);
    int _t_23 = 500;
    int _t_24 = myCar->function_calculateTax(myCar, _t_23);
    printf("%d\n", _t_24);
    bool _t_25 = true;
    myCar->isElectric = _t_25;
    int _t_26 = 500;
    int _t_27 = myCar->function_calculateTax(myCar, _t_26);
    printf("%d\n", _t_27);
    struct Vehicle* v = (struct Vehicle*) myCar;
    int _t_28 = 500;
    int _t_29 = v->function_calculateTax(v, _t_28);
    printf("%d\n", _t_29);
    int _t_30 = 1;
    int _t_31 = 2;
    int _t_32 = 3;
    int _t_33 = _t_31 * _t_32;
    int _t_34 = _t_30 + _t_33;
    int score = _t_34;
    printf("%d\n", score);
    int _t_35 = 7;
    bool _t_36 = score == _t_35;
    int _t_37 = 5;
    bool _t_38 = score < _t_37;
    bool _t_39 = !(_t_38);
    bool _t_40 = _t_36 && _t_39;
    bool flag = _t_40;
    if (!(flag)) goto if_else_3;
    {
    int _t_41 = 1;
    printf("%d\n", _t_41);
    }
    goto if_end_4;
    if_else_3:
    {
    int _t_42 = 0;
    printf("%d\n", _t_42);
    }
    if_end_4:
    int _t_43 = 10;
    int counter = _t_43;
    {
    bool _t_44 = true;
    bool counter = _t_44;
    if (!(counter)) goto if_else_5;
    {
    int _t_45 = 99;
    printf("%d\n", _t_45);
    }
    goto if_end_6;
    if_else_5:
    if_end_6:
    }
    printf("%d\n", counter);
    int _t_46 = 0;
    int i = _t_46;
    loop_start_7:
    int _t_47 = 10;
    bool _t_48 = i < _t_47;
    if (!(_t_48)) goto loop_end_8;
    {
    int _t_49 = 1;
    int _t_50 = i + _t_49;
    i = _t_50;
    int _t_51 = 2;
    bool _t_52 = i == _t_51;
    if (!(_t_52)) goto if_else_9;
    {
    goto loop_start_7;
    }
    goto if_end_10;
    if_else_9:
    if_end_10:
    int _t_53 = 5;
    bool _t_54 = i == _t_53;
    if (!(_t_54)) goto if_else_11;
    {
    goto loop_end_8;
    }
    goto if_end_12;
    if_else_11:
    if_end_12:
    printf("%d\n", i);
    }
    goto loop_start_7;
    loop_end_8:
    return 0;
}
