// Generated by AUJava Transpiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// Forward Struct Declarations
struct Counter;
struct Main;

// Struct Definitions
struct Counter {
};

struct Main {
};


// Global Static Fields
int Counter_val = 0;

// Function Forward Declarations
struct Counter* new_Counter();
struct Main* new_Main();
void Counter_addVal(int n);

// Constructors
struct Counter* new_Counter() {
    struct Counter *instance = (struct Counter *) malloc(sizeof(struct Counter));
    return instance;
}

struct Main* new_Main() {
    struct Main *instance = (struct Main *) malloc(sizeof(struct Main));
    return instance;
}


// Method Implementations
void Counter_addVal(int n) {
    int _t_2 = Counter_val + n;
    Counter_val = _t_2;
}


// Program Main Entry Point
int main() {
    int _t_1 = 100;
    Counter_val = _t_1;
    printf("%d\n", Counter_val);
    int _t_3 = 50;
    Counter_addVal(_t_3);
    printf("%d\n", Counter_val);
    return 0;
}
