// Generated by AUJava Transpiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// Forward Struct Declarations
struct Shape;
struct Circle;
struct Main;

// Struct Definitions
struct Shape {
    int id;
    int (*function_computeVal)(void *caller, int);
};

struct Circle {
    struct Shape super;
    int radius;
    int (*function_computeVal)(void *caller, int);
};

struct Main {
};


// Global Static Fields

// Function Forward Declarations
struct Shape* new_Shape();
struct Circle* new_Circle();
struct Main* new_Main();
int Shape_function_computeVal(void *caller, int base);
int Circle_function_computeVal(void *caller, int base);

// Constructors
struct Shape* new_Shape() {
    struct Shape *instance = (struct Shape *) malloc(sizeof(struct Shape));
    instance->function_computeVal = (void *) Shape_function_computeVal;
    return instance;
}

struct Circle* new_Circle() {
    struct Circle *instance = (struct Circle *) malloc(sizeof(struct Circle));
    struct Shape *parent_inst = new_Shape();
    instance->super = *parent_inst;
    free(parent_inst);
    instance->function_computeVal = (void *) Circle_function_computeVal;
    instance->super.function_computeVal = (void *) Circle_function_computeVal;
    return instance;
}

struct Main* new_Main() {
    struct Main *instance = (struct Main *) malloc(sizeof(struct Main));
    return instance;
}


// Method Implementations
int Shape_function_computeVal(void *caller, int base) {
    int _t_1 = 10;
    int _t_2 = base * _t_1;
    return _t_2;
}

int Circle_function_computeVal(void *caller, int base) {
    int _t_3 = 20;
    int _t_4 = base * _t_3;
    return _t_4;
}


// Program Main Entry Point
int main() {
    struct Circle *_t_5 = new_Circle();
    struct Circle* c = (struct Circle*) _t_5;
    int _t_6 = 50;
    c->super.id = _t_6;
    int _t_7 = 5;
    c->radius = _t_7;
    printf("%d\n", c->super.id);
    int _t_8 = 2;
    int _t_9 = c->function_computeVal(c, _t_8);
    printf("%d\n", _t_9);
    struct Shape* s = (struct Shape*) c;
    int _t_10 = 3;
    int _t_11 = s->function_computeVal(s, _t_10);
    printf("%d\n", _t_11);
    return 0;
}
