// Generated by AUJava Transpiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// Forward Struct Declarations
struct Main;

// Struct Definitions
struct Main {
};


// Global Static Fields

// Function Forward Declarations
struct Main* new_Main();

// Constructors
struct Main* new_Main() {
    struct Main *instance = (struct Main *) malloc(sizeof(struct Main));
    return instance;
}


// Method Implementations

// Program Main Entry Point
int main() {
    int _t_1 = 1;
    int _t_2 = 2;
    int _t_3 = 3;
    int _t_4 = _t_2 * _t_3;
    int _t_5 = _t_1 + _t_4;
    int x = _t_5;
    printf("%d\n", x);
    int _t_6 = 0;
    int i = _t_6;
    loop_start_1:
    int _t_7 = 5;
    bool _t_8 = i < _t_7;
    if (!(_t_8)) goto loop_end_2;
    {
    int _t_9 = 1;
    int _t_10 = i + _t_9;
    i = _t_10;
    int _t_11 = 2;
    bool _t_12 = i == _t_11;
    if (!(_t_12)) goto if_else_3;
    {
    goto loop_start_1;
    }
    goto if_end_4;
    if_else_3:
    if_end_4:
    int _t_13 = 4;
    bool _t_14 = i == _t_13;
    if (!(_t_14)) goto if_else_5;
    {
    goto loop_end_2;
    }
    goto if_end_6;
    if_else_5:
    if_end_6:
    printf("%d\n", i);
    }
    goto loop_start_1;
    loop_end_2:
    return 0;
}
