// Generated by AUJava Transpiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// Forward Struct Declarations
struct Teacher;
struct Student;
struct Main;

// Struct Definitions
struct Teacher {
    int id;
};

struct Student {
    struct Teacher* supervisor;
    void (*function_setSupervisor)(void *caller, struct Teacher*);
};

struct Main {
};


// Global Static Fields

// Function Forward Declarations
struct Teacher* new_Teacher();
struct Student* new_Student();
struct Main* new_Main();
void Student_function_setSupervisor(void *caller, struct Teacher* t);

// Constructors
struct Teacher* new_Teacher() {
    struct Teacher *instance = (struct Teacher *) malloc(sizeof(struct Teacher));
    return instance;
}

struct Student* new_Student() {
    struct Student *instance = (struct Student *) malloc(sizeof(struct Student));
    instance->function_setSupervisor = (void *) Student_function_setSupervisor;
    return instance;
}

struct Main* new_Main() {
    struct Main *instance = (struct Main *) malloc(sizeof(struct Main));
    return instance;
}


// Method Implementations
void Student_function_setSupervisor(void *caller, struct Teacher* t) {
    ((struct Student*) caller)->supervisor = t;
}


// Program Main Entry Point
int main() {
    struct Student *_t_1 = new_Student();
    struct Student* s = (struct Student*) _t_1;
    struct Teacher *_t_2 = new_Teacher();
    struct Teacher* t = (struct Teacher*) _t_2;
    int _t_3 = 1001;
    t->id = _t_3;
    s->function_setSupervisor(s, t);
    int _t_5 = 100;
    int i = _t_5;
    {
    bool _t_6 = true;
    bool i = _t_6;
    if (!(i)) goto if_else_1;
    {
    int _t_7 = 1;
    printf("%d\n", _t_7);
    }
    goto if_end_2;
    if_else_1:
    if_end_2:
    }
    printf("%d\n", i);
    return 0;
}
