package compiler.codegen;

import compiler.AUJavaBaseVisitor;
import compiler.AUJavaParser;
import compiler.symbol.ClassSymbol;
import compiler.symbol.MethodSymbol;
import compiler.symbol.Symbol;
import compiler.symbol.SymbolTable;
import compiler.symbol.Type;

import java.util.*;

public class CodeGeneratorVisitor extends AUJavaBaseVisitor<String> {
    private final SymbolTable symbolTable;
    private final StringBuilder forwardDecls = new StringBuilder();
    private final StringBuilder structDefs = new StringBuilder();
    private final StringBuilder globalVars = new StringBuilder();
    private final StringBuilder methodForwardDecls = new StringBuilder();
    private final StringBuilder methodImplementations = new StringBuilder();
    private final StringBuilder constructors = new StringBuilder();
    private final StringBuilder staticInits = new StringBuilder();
    private final StringBuilder mainFunction = new StringBuilder();

    private int tempVarCounter = 0;
    private int labelCounter = 0;
    private final Stack<String> loopStartLabels = new Stack<>();
    private final Stack<String> loopEndLabels = new Stack<>();

    public CodeGeneratorVisitor(SymbolTable symbolTable) {
        this.symbolTable = symbolTable;
    }

    private String newTemp() {
        return "_t_" + (++tempVarCounter);
    }

    private String newLabel(String prefix) {
        return prefix + "_" + (++labelCounter);
    }

    public String generateC() {
        StringBuilder fullCode = new StringBuilder();
        fullCode.append("// Generated by AUJava Transpiler\n");
        fullCode.append("#include <stdio.h>\n");
        fullCode.append("#include <stdlib.h>\n");
        fullCode.append("#include <stdbool.h>\n\n");

        fullCode.append("// Forward Struct Declarations\n");
        fullCode.append(forwardDecls);
        fullCode.append("\n// Struct Definitions\n");
        fullCode.append(structDefs);
        fullCode.append("\n// Global Static Fields\n");
        fullCode.append(globalVars);
        fullCode.append("\n// Function Forward Declarations\n");
        fullCode.append(methodForwardDecls);
        fullCode.append("\n// Constructors\n");
        fullCode.append(constructors);
        fullCode.append("\n// Method Implementations\n");
        fullCode.append(methodImplementations);
        fullCode.append("\n// Program Main Entry Point\n");
        fullCode.append(mainFunction);

        return fullCode.toString();
    }

    @Override
    public String visitProgram(AUJavaParser.ProgramContext ctx) {
        List<ClassSymbol> sortedClasses = getTopologicallySortedClasses();

        for (ClassSymbol cs : sortedClasses) {
            forwardDecls.append("struct ").append(cs.getName()).append(";\n");
        }

        for (ClassSymbol cs : sortedClasses) {
            generateClassStructAndConstructor(cs);
        }

        for (AUJavaParser.ClassDeclContext classCtx : ctx.classDecl()) {
            visitClassDecl(classCtx);
        }

        return generateC();
    }

    private List<ClassSymbol> getTopologicallySortedClasses() {
        List<ClassSymbol> result = new ArrayList<>();
        Set<String> visited = new HashSet<>();

        for (ClassSymbol cs : symbolTable.getClasses().values()) {
            visitClassForSort(cs, visited, result);
        }
        return result;
    }

    private void visitClassForSort(ClassSymbol cs, Set<String> visited, List<ClassSymbol> result) {
        if (cs == null || visited.contains(cs.getName())) return;
        if (cs.getParent() != null) {
            visitClassForSort(cs.getParent(), visited, result);
        }
        visited.add(cs.getName());
        result.add(cs);
    }

    private void generateClassStructAndConstructor(ClassSymbol cs) {
        structDefs.append("struct ").append(cs.getName()).append(" {\n");

        if (cs.getParent() != null) {
            structDefs.append("    struct ").append(cs.getParent().getName()).append(" super;\n");
        }

        for (Symbol field : cs.getDirectFields().values()) {
            if (field.isStatic()) {
                globalVars.append(mapTypeToC(field.getType())).append(" ")
                        .append(cs.getName()).append("_").append(field.getName()).append(" = 0;\n");
            } else {
                structDefs.append("    ").append(mapTypeToC(field.getType())).append(" ")
                        .append(field.getName()).append(";\n");
            }
        }

        Map<String, MethodSymbol> allInstanceMethods = getAllInstanceMethods(cs);
        for (MethodSymbol method : allInstanceMethods.values()) {
            structDefs.append("    ").append(mapTypeToC(method.getReturnType()))
                    .append(" (*function_").append(method.getName()).append(")(void *caller");
            for (Symbol param : method.getParameters()) {
                structDefs.append(", ").append(mapTypeToC(param.getType()));
            }
            structDefs.append(");\n");
        }

        structDefs.append("};\n\n");

        methodForwardDecls.append("struct ").append(cs.getName()).append("* new_")
                .append(cs.getName()).append("();\n");

        constructors.append("struct ").append(cs.getName()).append("* new_")
                .append(cs.getName()).append("() {\n");
        constructors.append("    struct ").append(cs.getName()).append(" *instance = (struct ")
                .append(cs.getName()).append(" *) malloc(sizeof(struct ").append(cs.getName()).append("));\n");

        if (cs.getParent() != null) {
            constructors.append("    struct ").append(cs.getParent().getName())
                    .append(" *parent_inst = new_").append(cs.getParent().getName()).append("();\n");
            constructors.append("    instance->super = *parent_inst;\n");
            constructors.append("    free(parent_inst);\n");
        }

        for (Map.Entry<String, MethodSymbol> entry : allInstanceMethods.entrySet()) {
            String mName = entry.getKey();
            MethodSymbol m = entry.getValue();

            ClassSymbol implClass = findMethodImplementationClass(cs, mName);
            String implFuncName = implClass.getName() + "_function_" + mName;

            constructors.append("    instance->function_").append(mName)
                    .append(" = (void *) ").append(implFuncName).append(";\n");

            if (cs.getParent() != null && cs.getParent().getMethod(mName) != null) {
                StringBuilder superChain = new StringBuilder("instance->super");
                ClassSymbol ancestor = cs.getParent();
                while (ancestor != null && ancestor.getMethod(mName) != null) {
                    constructors.append("    ").append(superChain).append(".function_")
                            .append(mName).append(" = (void *) ").append(implFuncName).append(";\n");
                    ancestor = ancestor.getParent();
                    superChain.append(".super");
                }
            }
        }

        constructors.append("    return instance;\n");
        constructors.append("}\n\n");
    }

    private Map<String, MethodSymbol> getAllInstanceMethods(ClassSymbol cs) {
        Map<String, MethodSymbol> map = new LinkedHashMap<>();
        if (cs.getParent() != null) {
            map.putAll(getAllInstanceMethods(cs.getParent()));
        }
        for (MethodSymbol m : cs.getDirectMethods().values()) {
            if (!m.isStatic()) {
                map.put(m.getName(), m);
            }
        }
        return map;
    }

    private ClassSymbol findMethodImplementationClass(ClassSymbol cs, String methodName) {
        ClassSymbol curr = cs;
        while (curr != null) {
            if (curr.getDirectMethods().containsKey(methodName)) {
                return curr;
            }
            curr = curr.getParent();
        }
        return cs;
    }

    @Override
    public String visitClassDecl(AUJavaParser.ClassDeclContext ctx) {
        String className = ctx.Identifier(0).getText();
        ClassSymbol cs = symbolTable.getClass(className);
        symbolTable.setCurrentClass(cs);

        for (AUJavaParser.ClassBodyMemberContext member : ctx.classBodyMember()) {
            if (member.fieldDecl() != null && member.fieldDecl().STATIC() != null && member.fieldDecl().ASSIGN() != null) {
                String fieldName = member.fieldDecl().Identifier().getText();
                CodeResult initRes = generateExprCode(member.fieldDecl().expr());
                staticInits.append(initRes.code);
                staticInits.append(className).append("_").append(fieldName).append(" = ").append(initRes.resultVar).append(";\n");
            } else if (member.mainMethodDecl() != null) {
                visitMainMethodDecl(member.mainMethodDecl());
            } else if (member.methodDecl() != null) {
                visitMethodDecl(member.methodDecl());
            }
        }

        symbolTable.setCurrentClass(null);
        return null;
    }

    @Override
    public String visitMainMethodDecl(AUJavaParser.MainMethodDeclContext ctx) {
        mainFunction.append("int main() {\n");
        symbolTable.enterScope();

        mainFunction.append(indent(staticInits.toString()));

        StringBuilder bodyCode = new StringBuilder();
        for (AUJavaParser.StatementContext stmt : ctx.statement()) {
            bodyCode.append(visit(stmt));
        }

        symbolTable.exitScope();
        mainFunction.append(indent(bodyCode.toString()));
        mainFunction.append("    return 0;\n");
        mainFunction.append("}\n");

        return null;
    }

    @Override
    public String visitMethodDecl(AUJavaParser.MethodDeclContext ctx) {
        String methodName = ctx.Identifier().getText();
        ClassSymbol cs = symbolTable.getCurrentClass();
        boolean isStatic = ctx.STATIC() != null;
        MethodSymbol method = cs.getDirectMethods().get(methodName);
        symbolTable.setCurrentMethod(method);
        symbolTable.enterScope();

        for (Symbol param : method.getParameters()) {
            symbolTable.declareVariable(param);
        }

        String funcName = isStatic ? cs.getName() + "_" + methodName : cs.getName() + "_function_" + methodName;
        String returnTypeC = mapTypeToC(method.getReturnType());

        StringBuilder signature = new StringBuilder();
        signature.append(returnTypeC).append(" ").append(funcName).append("(");
        if (!isStatic) {
            signature.append("void *caller");
            for (Symbol param : method.getParameters()) {
                signature.append(", ").append(mapTypeToC(param.getType())).append(" ").append(param.getName());
            }
        } else {
            int count = 0;
            for (Symbol param : method.getParameters()) {
                if (count++ > 0) signature.append(", ");
                signature.append(mapTypeToC(param.getType())).append(" ").append(param.getName());
            }
            if (method.getParameters().isEmpty()) {
                signature.append("void");
            }
        }
        signature.append(")");

        methodForwardDecls.append(signature).append(";\n");
        methodImplementations.append(signature).append(" {\n");

        StringBuilder bodyCode = new StringBuilder();
        if (!isStatic) {
            bodyCode.append("(void)caller;\n");
        }

        for (AUJavaParser.StatementContext stmt : ctx.statement()) {
            bodyCode.append(visit(stmt));
        }

        methodImplementations.append(indent(bodyCode.toString()));
        methodImplementations.append("}\n\n");

        symbolTable.exitScope();
        symbolTable.setCurrentMethod(null);
        return null;
    }

    // ==========================================
    // STATEMENTS CODE GENERATION
    // ==========================================

    @Override
    public String visitBlockStatement(AUJavaParser.BlockStatementContext ctx) {
        symbolTable.enterScope();
        StringBuilder code = new StringBuilder();
        code.append("{\n");
        for (AUJavaParser.StatementContext stmt : ctx.statement()) {
            code.append(visit(stmt));
        }
        code.append("}\n");
        symbolTable.exitScope();
        return code.toString();
    }

    @Override
    public String visitVarDeclStatement(AUJavaParser.VarDeclStatementContext ctx) {
        String varName = ctx.Identifier().getText();
        Type varType = resolveType(ctx.type());
        String typeC = mapTypeToC(varType);

        symbolTable.declareVariable(new Symbol(varName, varType));

        StringBuilder code = new StringBuilder();
        if (ctx.ASSIGN() != null && ctx.expr() != null) {
            CodeResult initRes = generateExprCode(ctx.expr());
            code.append(initRes.code);
            String cast = varType.isClass() ? "(" + typeC + ") " : "";
            code.append(typeC).append(" ").append(varName).append(" = ").append(cast).append(initRes.resultVar).append(";\n");
        } else {
            code.append(typeC).append(" ").append(varName).append(" = 0;\n");
        }
        return code.toString();
    }

    @Override
    public String visitIfStatement(AUJavaParser.IfStatementContext ctx) {
        String ifElseLabel = newLabel("if_else");
        String ifEndLabel = newLabel("if_end");

        CodeResult condRes = generateExprCode(ctx.expr());
        StringBuilder code = new StringBuilder();
        code.append(condRes.code);
        code.append("if (!(").append(condRes.resultVar).append(")) goto ").append(ifElseLabel).append(";\n");

        // Then block
        code.append(visit(ctx.statement(0)));
        code.append("goto ").append(ifEndLabel).append(";\n");

        // Else block
        code.append(ifElseLabel).append(":\n");
        if (ctx.statement().size() > 1) {
            code.append(visit(ctx.statement(1)));
        }
        code.append(ifEndLabel).append(":\n");

        return code.toString();
    }

    @Override
    public String visitWhileStatement(AUJavaParser.WhileStatementContext ctx) {
        String loopStart = newLabel("loop_start");
        String loopEnd = newLabel("loop_end");

        loopStartLabels.push(loopStart);
        loopEndLabels.push(loopEnd);

        StringBuilder code = new StringBuilder();
        code.append(loopStart).append(":\n");

        CodeResult condRes = generateExprCode(ctx.expr());
        code.append(condRes.code);
        code.append("if (!(").append(condRes.resultVar).append(")) goto ").append(loopEnd).append(";\n");

        code.append(visit(ctx.statement()));
        code.append("goto ").append(loopStart).append(";\n");
        code.append(loopEnd).append(":\n");

        loopStartLabels.pop();
        loopEndLabels.pop();

        return code.toString();
    }

    @Override
    public String visitBreakStatement(AUJavaParser.BreakStatementContext ctx) {
        if (!loopEndLabels.isEmpty()) {
            return "goto " + loopEndLabels.peek() + ";\n";
        }
        return "";
    }

    @Override
    public String visitContinueStatement(AUJavaParser.ContinueStatementContext ctx) {
        if (!loopStartLabels.isEmpty()) {
            return "goto " + loopStartLabels.peek() + ";\n";
        }
        return "";
    }

    @Override
    public String visitReturnStatement(AUJavaParser.ReturnStatementContext ctx) {
        if (ctx.expr() != null) {
            CodeResult res = generateExprCode(ctx.expr());
            return res.code + "return " + res.resultVar + ";\n";
        }
        return "return;\n";
    }

    @Override
    public String visitPrintStatement(AUJavaParser.PrintStatementContext ctx) {
        CodeResult res = generateExprCode(ctx.expr());
        return res.code + "printf(\"%d\\n\", " + res.resultVar + ");\n";
    }

    @Override
    public String visitExprStatement(AUJavaParser.ExprStatementContext ctx) {
        CodeResult res = generateExprCode(ctx.expr());
        return res.code;
    }

    // ==========================================
    // THREE-ADDRESS CODE (TAC) EXPRESSION CODEGEN
    // ==========================================

    private static class CodeResult {
        String code;
        String resultVar;

        CodeResult(String code, String resultVar) {
            this.code = code;
            this.resultVar = resultVar;
        }
    }

    private CodeResult generateExprCode(AUJavaParser.ExprContext ctx) {
        if (ctx instanceof AUJavaParser.IntLiteralExprContext) {
            String val = ctx.getText();
            String temp = newTemp();
            return new CodeResult("int " + temp + " = " + val + ";\n", temp);
        }

        if (ctx instanceof AUJavaParser.BoolLiteralExprContext) {
            String val = ctx.getText().equals("true") ? "true" : "false";
            String temp = newTemp();
            return new CodeResult("bool " + temp + " = " + val + ";\n", temp);
        }

        if (ctx instanceof AUJavaParser.VarExprContext) {
            String name = ctx.getText();
            Symbol varSym = symbolTable.resolveVariable(name);

            if (varSym != null && !varSym.isField()) {
                return new CodeResult("", name);
            }

            ClassSymbol curClass = symbolTable.getCurrentClass();
            if (curClass != null && curClass.getField(name) != null) {
                Symbol f = curClass.getField(name);
                if (f.isStatic()) {
                    return new CodeResult("", curClass.getName() + "_" + name);
                } else {
                    String access = resolveObjectFieldAccess(curClass, "((struct " + curClass.getName() + "*) caller)", name);
                    return new CodeResult("", access);
                }
            }
            return new CodeResult("", name);
        }

        if (ctx instanceof AUJavaParser.ThisExprContext) {
            ClassSymbol curClass = symbolTable.getCurrentClass();
            String cName = curClass != null ? curClass.getName() : "void";
            return new CodeResult("", "((struct " + cName + "*) caller)");
        }

        if (ctx instanceof AUJavaParser.ParenExprContext) {
            return generateExprCode(((AUJavaParser.ParenExprContext) ctx).expr());
        }

        if (ctx instanceof AUJavaParser.AssignExprContext) {
            AUJavaParser.AssignExprContext assignCtx = (AUJavaParser.AssignExprContext) ctx;
            CodeResult valRes = generateExprCode(assignCtx.value);
            CodeResult targetRes = generateExprCode(assignCtx.target);

            StringBuilder code = new StringBuilder();
            code.append(valRes.code);
            code.append(targetRes.code);
            code.append(targetRes.resultVar).append(" = ").append(valRes.resultVar).append(";\n");
            return new CodeResult(code.toString(), targetRes.resultVar);
        }

        if (ctx instanceof AUJavaParser.LogicalAndExprContext) {
            AUJavaParser.LogicalAndExprContext andCtx = (AUJavaParser.LogicalAndExprContext) ctx;
            CodeResult leftRes = generateExprCode(andCtx.left);
            CodeResult rightRes = generateExprCode(andCtx.right);
            String resVar = newTemp();
            String scEndLabel = newLabel("sc_end");

            StringBuilder code = new StringBuilder();
            code.append(leftRes.code);
            code.append("bool ").append(resVar).append(" = false;\n");
            code.append("if (!(").append(leftRes.resultVar).append(")) goto ").append(scEndLabel).append(";\n");
            code.append(rightRes.code);
            code.append(resVar).append(" = ").append(rightRes.resultVar).append(";\n");
            code.append(scEndLabel).append(":\n");
            return new CodeResult(code.toString(), resVar);
        }

        if (ctx instanceof AUJavaParser.LogicalOrExprContext) {
            AUJavaParser.LogicalOrExprContext orCtx = (AUJavaParser.LogicalOrExprContext) ctx;
            CodeResult leftRes = generateExprCode(orCtx.left);
            CodeResult rightRes = generateExprCode(orCtx.right);
            String resVar = newTemp();
            String scEndLabel = newLabel("sc_end");

            StringBuilder code = new StringBuilder();
            code.append(leftRes.code);
            code.append("bool ").append(resVar).append(" = true;\n");
            code.append("if (").append(leftRes.resultVar).append(") goto ").append(scEndLabel).append(";\n");
            code.append(rightRes.code);
            code.append(resVar).append(" = ").append(rightRes.resultVar).append(";\n");
            code.append(scEndLabel).append(":\n");
            return new CodeResult(code.toString(), resVar);
        }

        if (ctx instanceof AUJavaParser.AdditiveExprContext ||
            ctx instanceof AUJavaParser.MultiplicativeExprContext ||
            ctx instanceof AUJavaParser.RelationalExprContext ||
            ctx instanceof AUJavaParser.EqualityExprContext) {

            String op = getOpFromBinaryExpr(ctx);
            AUJavaParser.ExprContext leftCtx = getLeftExpr(ctx);
            AUJavaParser.ExprContext rightCtx = getRightExpr(ctx);

            CodeResult leftRes = generateExprCode(leftCtx);
            CodeResult rightRes = generateExprCode(rightCtx);

            String temp = newTemp();
            String typeC = (op.equals("==") || op.equals("!=") || op.equals("<") || op.equals("<=") || op.equals(">") || op.equals(">=")) ? "bool" : "int";

            StringBuilder code = new StringBuilder();
            code.append(leftRes.code);
            code.append(rightRes.code);
            code.append(typeC).append(" ").append(temp).append(" = ").append(leftRes.resultVar).append(" ").append(op).append(" ").append(rightRes.resultVar).append(";\n");

            return new CodeResult(code.toString(), temp);
        }

        if (ctx instanceof AUJavaParser.UnaryExprContext) {
            AUJavaParser.UnaryExprContext uCtx = (AUJavaParser.UnaryExprContext) ctx;
            CodeResult subRes = generateExprCode(uCtx.expr());
            String temp = newTemp();
            String op = uCtx.op.getText();
            String typeC = op.equals("!") ? "bool" : "int";

            String code = subRes.code + typeC + " " + temp + " = " + op + "(" + subRes.resultVar + ");\n";
            return new CodeResult(code, temp);
        }

        if (ctx instanceof AUJavaParser.NewObjectExprContext) {
            AUJavaParser.NewObjectExprContext newCtx = (AUJavaParser.NewObjectExprContext) ctx;
            String className = newCtx.Identifier().getText();
            String temp = newTemp();
            String code = "struct " + className + " *" + temp + " = new_" + className + "();\n";
            return new CodeResult(code, temp);
        }

        if (ctx instanceof AUJavaParser.FieldAccessExprContext) {
            AUJavaParser.FieldAccessExprContext fieldCtx = (AUJavaParser.FieldAccessExprContext) ctx;
            CodeResult targetRes = generateExprCode(fieldCtx.expr());
            String fieldName = fieldCtx.Identifier().getText();

            String text = fieldCtx.expr().getText();
            ClassSymbol staticClass = symbolTable.getClass(text);
            if (staticClass != null && staticClass.getField(fieldName) != null && staticClass.getField(fieldName).isStatic()) {
                return new CodeResult("", staticClass.getName() + "_" + fieldName);
            }

            ClassSymbol targetClass = symbolTable.getClass(resolveExprTypeName(fieldCtx.expr()));
            String access = resolveObjectFieldAccess(targetClass, targetRes.resultVar, fieldName);
            return new CodeResult(targetRes.code, access);
        }

        if (ctx instanceof AUJavaParser.MethodCallExprContext) {
            AUJavaParser.MethodCallExprContext mCtx = (AUJavaParser.MethodCallExprContext) ctx;
            CodeResult targetRes = generateExprCode(mCtx.expr());
            String methodName = mCtx.Identifier().getText();

            String text = mCtx.expr().getText();
            ClassSymbol staticClass = symbolTable.getClass(text);
            if (staticClass != null && staticClass.getMethod(methodName) != null && staticClass.getMethod(methodName).isStatic()) {
                StringBuilder argsCode = new StringBuilder();
                List<String> argVars = new ArrayList<>();
                if (mCtx.arguments() != null) {
                    for (AUJavaParser.ExprContext argExpr : mCtx.arguments().expr()) {
                        CodeResult ar = generateExprCode(argExpr);
                        argsCode.append(ar.code);
                        argVars.add(ar.resultVar);
                    }
                }
                String temp = newTemp();
                MethodSymbol ms = staticClass.getMethod(methodName);
                String returnTypeC = mapTypeToC(ms.getReturnType());

                StringBuilder callCode = new StringBuilder();
                callCode.append(argsCode);
                if (!returnTypeC.equals("void")) {
                    callCode.append(returnTypeC).append(" ").append(temp).append(" = ");
                }
                callCode.append(staticClass.getName()).append("_").append(methodName).append("(");
                for (int i = 0; i < argVars.size(); i++) {
                    if (i > 0) callCode.append(", ");
                    callCode.append(argVars.get(i));
                }
                callCode.append(");\n");
                return new CodeResult(callCode.toString(), returnTypeC.equals("void") ? "" : temp);
            }

            // Instance method call via function pointer
            StringBuilder argsCode = new StringBuilder();
            List<String> argVars = new ArrayList<>();
            if (mCtx.arguments() != null) {
                for (AUJavaParser.ExprContext argExpr : mCtx.arguments().expr()) {
                    CodeResult ar = generateExprCode(argExpr);
                    argsCode.append(ar.code);
                    argVars.add(ar.resultVar);
                }
            }

            ClassSymbol targetClass = symbolTable.getClass(resolveExprTypeName(mCtx.expr()));
            MethodSymbol ms = targetClass != null ? targetClass.getMethod(methodName) : null;
            String returnTypeC = ms != null ? mapTypeToC(ms.getReturnType()) : "int";

            String temp = newTemp();
            StringBuilder callCode = new StringBuilder();
            callCode.append(targetRes.code);
            callCode.append(argsCode);

            if (!returnTypeC.equals("void")) {
                callCode.append(returnTypeC).append(" ").append(temp).append(" = ");
            }
            callCode.append(targetRes.resultVar).append("->function_").append(methodName).append("(")
                    .append(targetRes.resultVar);
            for (String av : argVars) {
                callCode.append(", ").append(av);
            }
            callCode.append(");\n");

            return new CodeResult(callCode.toString(), returnTypeC.equals("void") ? "" : temp);
        }

        if (ctx instanceof AUJavaParser.LocalMethodCallExprContext) {
            AUJavaParser.LocalMethodCallExprContext lmCtx = (AUJavaParser.LocalMethodCallExprContext) ctx;
            String methodName = lmCtx.Identifier().getText();
            ClassSymbol curClass = symbolTable.getCurrentClass();
            MethodSymbol ms = curClass != null ? curClass.getMethod(methodName) : null;

            StringBuilder argsCode = new StringBuilder();
            List<String> argVars = new ArrayList<>();
            if (lmCtx.arguments() != null) {
                for (AUJavaParser.ExprContext argExpr : lmCtx.arguments().expr()) {
                    CodeResult ar = generateExprCode(argExpr);
                    argsCode.append(ar.code);
                    argVars.add(ar.resultVar);
                }
            }

            String returnTypeC = ms != null ? mapTypeToC(ms.getReturnType()) : "void";
            String temp = newTemp();

            StringBuilder callCode = new StringBuilder();
            callCode.append(argsCode);
            if (!returnTypeC.equals("void")) {
                callCode.append(returnTypeC).append(" ").append(temp).append(" = ");
            }

            if (ms != null && ms.isStatic()) {
                callCode.append(curClass.getName()).append("_").append(methodName).append("(");
                for (int i = 0; i < argVars.size(); i++) {
                    if (i > 0) callCode.append(", ");
                    callCode.append(argVars.get(i));
                }
                callCode.append(");\n");
            } else {
                callCode.append("((struct ").append(curClass.getName()).append("*) caller)->function_")
                        .append(methodName).append("(caller");
                for (String av : argVars) {
                    callCode.append(", ").append(av);
                }
                callCode.append(");\n");
            }

            return new CodeResult(callCode.toString(), returnTypeC.equals("void") ? "" : temp);
        }

        return new CodeResult("", ctx.getText());
    }

    private String resolveObjectFieldAccess(ClassSymbol cs, String varName, String fieldName) {
        if (cs == null) return varName + "->" + fieldName;
        ClassSymbol curr = cs;
        StringBuilder sb = new StringBuilder(varName);
        boolean first = true;
        while (curr != null) {
            if (curr.getDirectFields().containsKey(fieldName)) {
                return sb.toString() + (first ? "->" : ".") + fieldName;
            }
            curr = curr.getParent();
            sb.append(first ? "->super" : ".super");
            first = false;
        }
        return varName + "->" + fieldName;
    }

    private String resolveExprTypeName(AUJavaParser.ExprContext expr) {
        String text = expr.getText();
        if (text.equals("this") && symbolTable.getCurrentClass() != null) {
            return symbolTable.getCurrentClass().getName();
        }
        Symbol s = symbolTable.resolveVariable(text);
        if (s != null && s.getType().isClass()) {
            return s.getType().getName();
        }
        ClassSymbol cs = symbolTable.getClass(text);
        if (cs != null) return cs.getName();
        return "";
    }

    private String getOpFromBinaryExpr(AUJavaParser.ExprContext ctx) {
        if (ctx instanceof AUJavaParser.AdditiveExprContext) return ((AUJavaParser.AdditiveExprContext) ctx).op.getText();
        if (ctx instanceof AUJavaParser.MultiplicativeExprContext) return ((AUJavaParser.MultiplicativeExprContext) ctx).op.getText();
        if (ctx instanceof AUJavaParser.RelationalExprContext) return ((AUJavaParser.RelationalExprContext) ctx).op.getText();
        if (ctx instanceof AUJavaParser.EqualityExprContext) return ((AUJavaParser.EqualityExprContext) ctx).op.getText();
        if (ctx instanceof AUJavaParser.LogicalAndExprContext) return "&&";
        if (ctx instanceof AUJavaParser.LogicalOrExprContext) return "||";
        return "+";
    }

    private AUJavaParser.ExprContext getLeftExpr(AUJavaParser.ExprContext ctx) {
        if (ctx instanceof AUJavaParser.AdditiveExprContext) return ((AUJavaParser.AdditiveExprContext) ctx).left;
        if (ctx instanceof AUJavaParser.MultiplicativeExprContext) return ((AUJavaParser.MultiplicativeExprContext) ctx).left;
        if (ctx instanceof AUJavaParser.RelationalExprContext) return ((AUJavaParser.RelationalExprContext) ctx).left;
        if (ctx instanceof AUJavaParser.EqualityExprContext) return ((AUJavaParser.EqualityExprContext) ctx).left;
        if (ctx instanceof AUJavaParser.LogicalAndExprContext) return ((AUJavaParser.LogicalAndExprContext) ctx).left;
        if (ctx instanceof AUJavaParser.LogicalOrExprContext) return ((AUJavaParser.LogicalOrExprContext) ctx).left;
        return null;
    }

    private AUJavaParser.ExprContext getRightExpr(AUJavaParser.ExprContext ctx) {
        if (ctx instanceof AUJavaParser.AdditiveExprContext) return ((AUJavaParser.AdditiveExprContext) ctx).right;
        if (ctx instanceof AUJavaParser.MultiplicativeExprContext) return ((AUJavaParser.MultiplicativeExprContext) ctx).right;
        if (ctx instanceof AUJavaParser.RelationalExprContext) return ((AUJavaParser.RelationalExprContext) ctx).right;
        if (ctx instanceof AUJavaParser.EqualityExprContext) return ((AUJavaParser.EqualityExprContext) ctx).right;
        if (ctx instanceof AUJavaParser.LogicalAndExprContext) return ((AUJavaParser.LogicalAndExprContext) ctx).right;
        if (ctx instanceof AUJavaParser.LogicalOrExprContext) return ((AUJavaParser.LogicalOrExprContext) ctx).right;
        return null;
    }

    private String mapTypeToC(Type type) {
        if (type.getKind() == Type.Kind.INT) return "int";
        if (type.getKind() == Type.Kind.BOOLEAN) return "bool";
        if (type.getKind() == Type.Kind.VOID) return "void";
        if (type.getKind() == Type.Kind.CLASS) return "struct " + type.getName() + "*";
        return "int";
    }

    private Type resolveType(AUJavaParser.TypeContext ctx) {
        if (ctx.INT() != null) return Type.INT_TYPE;
        if (ctx.BOOLEAN() != null) return Type.BOOL_TYPE;
        if (ctx.Identifier() != null) return new Type(Type.Kind.CLASS, ctx.Identifier().getText());
        return Type.ERROR_TYPE;
    }

    private String indent(String text) {
        String[] lines = text.split("\n");
        StringBuilder sb = new StringBuilder();
        for (String line : lines) {
            if (!line.trim().isEmpty()) {
                sb.append("    ").append(line).append("\n");
            }
        }
        return sb.toString();
    }
}
