// Generated by AUJava Transpiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// Forward Struct Declarations
struct Main;

// Struct Definitions
struct Main {
};


// Global Static Fields

// Function Forward Declarations
struct Main* new_Main();

// Constructors
struct Main* new_Main() {
    struct Main *instance = (struct Main *) malloc(sizeof(struct Main));
    return instance;
}


// Method Implementations

// Program Main Entry Point
int main() {
    int _t_1 = 10;
    int x = _t_1;
    int _t_2 = 20;
    int _t_3 = 2;
    int _t_4 = x * _t_3;
    int _t_5 = _t_2 + _t_4;
    int y = _t_5;
    bool _t_6 = true;
    bool flag = _t_6;
    int _t_7 = 30;
    bool _t_8 = y > _t_7;
    bool _t_9 = flag && _t_8;
    if (!(_t_9)) goto if_else_1;
    {
    int _t_10 = 1;
    int _t_11 = x + _t_10;
    x = _t_11;
    }
    goto if_end_2;
    if_else_1:
    {
    int _t_12 = 0;
    x = _t_12;
    }
    if_end_2:
    loop_start_3:
    int _t_13 = 15;
    bool _t_14 = x < _t_13;
    if (!(_t_14)) goto loop_end_4;
    {
    printf("%d\n", x);
    int _t_15 = 1;
    int _t_16 = x + _t_15;
    x = _t_16;
    int _t_17 = 13;
    bool _t_18 = x == _t_17;
    if (!(_t_18)) goto if_else_5;
    {
    goto loop_start_3;
    }
    goto if_end_6;
    if_else_5:
    if_end_6:
    int _t_19 = 14;
    bool _t_20 = x == _t_19;
    if (!(_t_20)) goto if_else_7;
    {
    goto loop_end_4;
    }
    goto if_end_8;
    if_else_7:
    if_end_8:
    }
    goto loop_start_3;
    loop_end_4:
    return 0;
}
