// Generated by AUJava Transpiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// Forward Struct Declarations
struct Animal;
struct Dog;
struct Main;

// Struct Definitions
struct Animal {
    int age;
    int (*function_getAge)(void *caller);
    void (*function_setAge)(void *caller, int);
};

struct Dog {
    struct Animal super;
    bool isFriendly;
    int (*function_getAge)(void *caller);
    void (*function_setAge)(void *caller, int);
    void (*function_speak)(void *caller);
};

struct Main {
};


// Global Static Fields
int Dog_dogCount = 0;

// Function Forward Declarations
struct Animal* new_Animal();
struct Dog* new_Dog();
struct Main* new_Main();
void Animal_function_setAge(void *caller, int a);
int Animal_function_getAge(void *caller);
void Dog_function_speak(void *caller);

// Constructors
struct Animal* new_Animal() {
    struct Animal *instance = (struct Animal *) malloc(sizeof(struct Animal));
    instance->function_getAge = (void *) Animal_function_getAge;
    instance->function_setAge = (void *) Animal_function_setAge;
    return instance;
}

struct Dog* new_Dog() {
    struct Dog *instance = (struct Dog *) malloc(sizeof(struct Dog));
    struct Animal *parent_inst = new_Animal();
    instance->super = *parent_inst;
    free(parent_inst);
    instance->function_getAge = (void *) Animal_function_getAge;
    instance->super.function_getAge = (void *) Animal_function_getAge;
    instance->function_setAge = (void *) Animal_function_setAge;
    instance->super.function_setAge = (void *) Animal_function_setAge;
    instance->function_speak = (void *) Dog_function_speak;
    return instance;
}

struct Main* new_Main() {
    struct Main *instance = (struct Main *) malloc(sizeof(struct Main));
    return instance;
}


// Method Implementations
void Animal_function_setAge(void *caller, int a) {
    ((struct Animal*) caller)->age = a;
}

int Animal_function_getAge(void *caller) {
    return ((struct Animal*) caller)->age;
}

void Dog_function_speak(void *caller) {
    int _t_2 = 101;
    printf("%d\n", _t_2);
}


// Program Main Entry Point
int main() {
    int _t_1 = 0;
    Dog_dogCount = _t_1;
    struct Dog *_t_3 = new_Dog();
    struct Dog* d = (struct Dog*) _t_3;
    int _t_4 = 5;
    d->function_setAge(d, _t_4);
    bool _t_6 = true;
    d->isFriendly = _t_6;
    int _t_7 = d->function_getAge(d);
    printf("%d\n", _t_7);
    return 0;
}
